name: quarkus-template

services:
  quarkus_template:
    build:
      context: .
      dockerfile: Dockerfile.native
    image: quarkus-template:1.0.0
    container_name: quarkus-template
    restart: unless-stopped
    ports:
      - 3005:3005
    networks:
      - net

networks:
  net:
    driver: bridge
